version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/kabuol
      - bundle:/kabuol/vendor/bundle
    working_dir: /kabuol
    stdin_open: true
    tty: true
volumes:
  bundle:
